apiVersion: v1
kind: Service
metadata:
  name: api-requests-counter
  namespace: api-requests-counter
spec:
  selector:
    app: api-requests-counter
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
  